name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    env:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        pytest --cov=src tests/
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build and deploy with SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name flask-app-stack --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --parameter-overrides RedisHost=redis
